sudo: false

language: cpp

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - libcpprest-dev
      - libsodium-dev
      - libopus-dev

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
