language: cpp

jobs:
  include:
    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
            - libcpprest-dev
            - libsodium-dev
            - libopus-dev
      env:
        - MATRIX_EVAL="CC=gcc-9 CXX=g++-9"

    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - llvm-toolchain-bionic-9
          packages:
            - clang-9
            - libcpprest-dev
            - libsodium-dev
            - libopus-dev
      env:
        - MATRIX_EVAL="CC=clang-9 CXX=clang++-9"

    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - llvm-toolchain-bionic-10
          packages:
            - clang-10
            - libcpprest-dev
            - libsodium-dev
            - libopus-dev
      env:
        - MATRIX_EVAL="CC=clang-10 CXX=clang++-10"

before_script:
  - eval "${MATRIX_EVAL}"

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
