os: linux

dist: bionic

language: cpp

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-bionic-9
    packages:
      - libcpprest-dev
      - libsodium-dev
      - libopus-dev
      - gcc-9
      - g++-9
      - clang-9

script:
  - update-alternatives --set gcc "/usr/bin/gcc-9"
  - update-alternatives --set g++ "/usr/bin/g++-9"
  - update-alternatives --set clang "/usr/bin/clang-9"
  - update-alternatives --set clang++ "/usr/bin/clang++-9"
  - mkdir build
  - cd build
  - cmake ..
  - make
