os:
  - linux
  - osx

dist: bionic
osx_image: xcode11

language: cpp

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - libcpprest-dev
      - libsodium-dev
      - libopus-dev
  homebrew:
    packages:
      - cpprestsdk
      - libsodium
      - opus

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
