os:
  - linux
  - osx

dist: bionic

language: cpp

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - libcpprest-dev
      - libsodium-dev
      - libopus-dev
  homebrew:
    packages:
      - cpprestsdk
      - libsodium
      - libopus

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
