#pragma once
#include <iostream>

#include "DiscordObject.h"
#include "User.h"
#include "Channel.h"

namespace DiscordCPP {

	using namespace std;
	using namespace web::json;
	using namespace utility;

	namespace MessageType {
		enum MessageType {
			DEFAULT,
			RECIPIENT_ADD,
			RECIPIENT_REMOVE,
			CALL,
			CHANNEL_NAME_CHANGE,
			CHANNEL_ICON_CHANGE,
			CHANNEL_PINNED_MESSAGE,
			GUILD_MEMBER_JOIN
		};
	}

	class Message : DiscordObject {
	public:
		///the channel the message was sent in
		Channel *channel = NULL;
		///The author of this message
		User *author = NULL;
		///The content of this message
		string content;	
		//ISO8601 timestamp
		///when the message was created
		string timestamp;
		//ISO8601 timestamp
		///when the message was edited
		string edited_timestamp;
		///true, if this is a tts message
		bool tts;
		///true, if everyone is mentioned
		bool mention_everyone;
		///array of mentioned users
		vector<User *> mentions;
		//vector<Role> mention_roles;
		//vector<Attachments> attachments;
		//vector<Embed> embeds;
		//vector<Reaction> reactions;
		///true, if this message has been pinned
		bool pinned;
		///the webhook id, if the message was generated by a webhook
		string webhook_id;	//snowflake
		///the type of the messsage
		int type;
		//MessageAcivity activity;
		//MessageApplication application;

		__declspec(dllexport) Message(value data, string_t token);
		__declspec(dllexport) Message(const Message &old);
		__declspec(dllexport) Message();
		__declspec(dllexport) ~Message();

		///Edit this message
		__declspec(dllexport) Message edit(string content);
	};

}